# Generated by Django 5.0.4 on 2026-02-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Payment'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
